### ISSUE TITLE
Dont work on NC19

### ISSUE THREAD

**Issue by XChrissX** [v1r0x/files_3d#19]
Es Arbeitet leider nicht unter NC19. 

Der Viewer öffnet sich aber erstellt bei keiner meiner 7000 STL oder OBJ eine Vorschau

**Comment by haarp** [comment]
Currently, 0.3.1 is broken. I had to downgrade to 0.3.0 to make it work again.

Nextcloud will show the preview overlay but will not render anything.

The trick of disabling, re-enablign the app I used in #14 doesn't seem to work here either.

**Comment by v1r0x** [comment]
This is hopefully fixed in 0.3.2 I'll release it to the appstore soon. In the meantime it would be great if you could test the new release

**Comment by msegec** [comment]
Hi V1r0x, 

I could not find a upworker to help me develop this code into something with more features, however. It appears with more research into the integration, I found some of the areas I need to work on. 

I will start doing some work in my Fork over the weeks and occasionally tag you :)

**Comment by haarp** [comment]
> In the meantime it would be great if you could test the new release

Great news, thanks!

I just tested in on my NC 19.0.3 install. Unfortunately, for me #14 is back. I can't solve it by disabling/re-enabling the app either.

Do I need to build something? I merely extracted the v0.3.2-beta release archive into the same place the older version used to be.

**Comment by v1r0x** [comment]
Yes, currently you have to build the app yourself with
```bash
npm install
npm run build
```

After that it should work :crossed_fingers:

**Comment by mazabalgo** [comment]
Hi

I do that and i have errors

npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/storage.bylapera.com/html/apps/files_3d/npm-debug.log

**Comment by msegec** [comment]
same error as above Virox

**Comment by v1r0x** [comment]
Finally released 0.3.2 to the app store. Sorry for the delay! Hope it works for you folks?

**Comment by haarp** [comment]
Works for me. Thank you!

**Comment by essys** [comment]
Rendering or at least colours of the objects are not optimized.
Here for example this is a screenshot of a rubber duck stl file.
The duck itself is just black. 
Should I open a separate ticket for that problem?
EDIT: NC19.0.3 and "files 3d" in v0.3.2

![Screenshot 2020-09-30 at 10 34 51](https://user-images.githubusercontent.com/7117619/94662504-c5516680-0308-11eb-9d7a-0c32ebfc5d58.png)

**Comment by v1r0x** [comment]
@essys yes, please. Or you can comment on #9 since this is also related to lighting.

**Comment by v1r0x** [comment]
Since it works again in 0.3.2 I'm closing this issue
