### ISSUE TITLE
Blank preview

### ISSUE THREAD

**Issue by tetsuo76** [v1r0x/files_3d#21]
I am getting a blank preview after installing the app from the nextcloud app store (NC19). I tried using a few sample .obj files from [here](https://people.sc.fsu.edu/~jburkardt/data/obj/obj.html). I also tried a couple of .dae file without any luck. 

Any suggestions?

**Comment by v1r0x** [comment]
Seems to be the same problem as described in #19

**Comment by v1r0x** [comment]
Please check new 0.3.2 version and update in #19
