### ISSUE TITLE
Stl not redenring

### ISSUE THREAD

**Issue by EduardoOliveira** [v1r0x/files_3d#22]
Hi,
Stl files get downloaded but after I get the following error in the console 
```three.module.js:8692 THREE.Material: 'vertexColors' parameter is undefined.```

The loading stops but there is nothing rendered only the "black" overlay of the gallery.

I'm running a prety clean install using the official docker-compose, current version Nextcloud 19.0.1

For  the stl's to get recognised by the app I had to disable and enable again.

Any ideas? thank you

**Comment by v1r0x** [comment]
Currently the needed steps are only run after an upgrade/re-enabling of the app. I'm already looking for a solution.

The problem with a blank window is already described in #21 #20 and #19 Will look into it

**Comment by v1r0x** [comment]
Please check new 0.3.2 version and update in #19
