### ISSUE TITLE
Initial viewing angle/zoom level confusing

### ISSUE THREAD

**Issue by haarp** [v1r0x/files_3d#24]
When first opening a file, it's usually zoomed in and with the grid perpendicular to the viewing angle. This makes things a bit hard for my users to figure out. IMO it would be better if the initial viewing angle was isometric and the view zoomed out enough to make out the part you're viewing.

Case in point:

Initial view (you can't see the part at all as the view is through the hole):
![Screenshot_2020-09-27_19-33-43](https://user-images.githubusercontent.com/781030/94371666-72a16000-00f8-11eb-90c6-2238106033fe.png)

Suggested initial view:
![Screenshot_2020-09-27_19-34-06](https://user-images.githubusercontent.com/781030/94371668-77661400-00f8-11eb-8f92-63abd01feac5.png)

Thanks a lot! This is a really useful app for us, keep it up :)

**Comment by v1r0x** [comment]
Thanks for your input. That's a good point.
I did something similar for another project, so shouldn't be too hard to do :)

**Comment by demonlibra** [comment]
Very hope this functionality will be realeased.

**Comment by Revel8804** [comment]
This app is amazing and very useful. Thank you.

I would like the ability to change the grid size. If you could point me in the right direction as to where that is for the code. I can play around and see what I can figure out.

One thing that I was having trouble with, is finding the location of the following.
Could be as simple as I have not finished my coffee, but who knows.

`import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'`

**Comment by DerekL0576** [comment]
Need this. 👍

**Comment by csicar** [comment]
I'll give implementing this a try

**Comment by demonlibra** [comment]
Are you sure that file Files3d.vue in line 295 is correct?

**Comment by csicar** [comment]
I guess you are referring to the PR right? I don't see what would be wrong in line 295...

**Comment by demonlibra** [comment]
Maybe 295, 296, 297 and 298 must be in one line.
Sorry if I wrong.

**Comment by demonlibra** [comment]
Checking with NextCloud 20.0.8
Looks good.
Thanks for your job.

**Comment by v1r0x** [comment]
@csicar Thanks for working on this! I wanted to work a little more on the app again in the coming weeks and make it compatible with latest NC version and implement a couple of features.
From looking at your code it looks good 👍 Will give it a try and merge it then. So this will be in the next release! 🎉

**Comment by csicar** [comment]
Awesome! Thank you for creating `files_3d`.

Looking forward to have that available in my NC instance :)

**Comment by duke2421** [comment]
I tried the code from @csicar and it is working very well. I also changed the workpiece color. 
Very nice. Here you can see it on my NC21 (with PHP7.4): https://duke24.badberg-online.de/s/ExYmtiXYfX4LSpx?dir=undefined&openfile=4439544

Looking forward to new releases from you and thanks for the great work.
