### ISSUE TITLE
[feature request] add ply support

### ISSUE THREAD

**Issue by flixr** [v1r0x/files_3d#26]
It would be great if ply would be supported as well.
There seems to be a loader in threejs:
* https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_ply.html
* https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/PLYLoader.js

**Comment by v1r0x** [comment]
As long as there's already a loader in threejs, it's fairly easy to add to the next release :wink:

**Comment by v1r0x** [comment]
Fixed via #29 in v0.3.3 (should be available in the appstore in a couple of hours)

**Comment by flixr** [comment]
Thx!
