### ISSUE TITLE
It does not work (mime stuff)

### ISSUE THREAD

**Issue by gerroon** [v1r0x/files_3d#3]
Hi

I installed it and did the recommended mime stuff and run the occ command to update the mime. Every step was succesful however I can't even open a simple .obj file.

How is this supposed to work exactly? I click on an .obj and opens it in a 3d viewer? Show up only in gallery? When I click on a .obj the browser tries to download it instead.

I am using it on Debian x64, NC 15, Apache/2.4.37, mariadb  Ver 15.1 Distrib 10.1.37-MariaDB

**Comment by v1r0x** [comment]
Unfortunately, you have to re-upload your files after the mime stuff. Does this fix your problem?

**Comment by gerroon** [comment]
I see, let me try that


OK  i copied a new .obj to the root (synced with the desktop app). I then click on the obj , the browser tries to download it.

Edit: Uploading from the browser did not work either, so I am not sure about how to make it work.

**Comment by v1r0x** [comment]
Did you check for any typos or wrong paths?

The mimemapping file should be `nextcloud/config/mimetypemapping.json` with
```json
{
"dae": ["model/vnd.collada+xml"],
"fbx": ["model/fbx-dummy"],
"gltf": ["model/gltf-binary", "model/gltf+json"],
"obj": ["model/obj-dummy"]
}
```

**Comment by gerroon** [comment]
Yeah the path is right and I used your recommended .json file

```
cat /var/www/html/nc/config/mimetypemapping.json 

"dae": ["model/vnd.collada+xml"],
"fbx": ["model/fbx-dummy"],
"gltf": ["model/gltf-binary", "model/gltf+json"],
"obj": ["model/obj-dummy"]

 ```

**Comment by v1r0x** [comment]
It looks like you're missing the `{` and `}` around the four entries

**Comment by gerroon** [comment]
Thanks, I copied from the Readme which does not show the braces. Maybe that should be added to the readme in the Github root?

**Comment by gerroon** [comment]
Ok it works now, this is nice. However the lighting seems messed up? See the image

<a href="https://i.imgur.com/7FqoZsO.png">
  <img src="https://imgur.com/7FqoZsOl.png" />
</a>

**Comment by v1r0x** [comment]
Readme is updated, sorry for the delay.



> Ok it works now, this is nice. However the lighting seems messed up? See the image

You mean the missing shadows?

**Comment by gerroon** [comment]
My guess is shading is a bit wrong when the model is large.

**Comment by v1r0x** [comment]
I'm closing this in favor of #9
