### ISSUE TITLE
Support for GLB

### ISSUE THREAD

**Issue by hemkantSplat** [v1r0x/files_3d#32]
Hi,

I see that you already have support for GLTF working, can you also add GLB support? it should work by default as three.js uses same loader for GLTF and GLB but I cant seem to make it work.

Thanks

**Comment by dschie** [comment]
renaming the file to .gltf already works. threejs seems to figure out the correct file type just fine. So maybe just adding the file extension to whatever list all it takes to make it work. Problem is, i cant seem to find the correct list. main.js already contains the correct mime-type ```model/gltf-binary```, but it looks like thats not enough.
