### ISSUE TITLE
Release missing at 0.4.0

### ISSUE THREAD

**Issue by ggPeti** [v1r0x/files_3d#50]
Hey @v1r0x, amazing work with this app. I noticed that the release tarball is missing with version 0.4.0. Is there any chance you can upload a new release, maybe support Nextcloud 23 as well?

**Comment by v1r0x** [comment]
Thanks for the info! I will release a new version (0.5) on github and nc appstore with updated deps and support for nc 21-23 this week. I won't add 0.4 to the appstore, because 0.5 should be enough, right?

**Comment by ggPeti** [comment]
Sounds about right!
