### ISSUE TITLE
[FEAT] Nextcloud v24 support

### ISSUE THREAD

**Issue by facorazza** [v1r0x/files_3d#65]
Is Nextcloud 24 supported?

**Comment by Thesola10** [comment]
The app installs fine, but opening 3D files doesn't appear to work. Tested with `dae`, `fbx` and `stl`, all of which were working on NC23

**Comment by Simbaclaws** [comment]
Same counts for ```obj```

I would love to be able to use this app within nextcloud 24, as I don't have a 23 version setup as of now...

Are there any logs where I can check why the app is not working? And perhaps help contribute to a solution if possible?
All I see in the console is moment and jquery deprecations...

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by LightTemplar** [comment]
There is already v25.

**Comment by v1r0x** [comment]
> Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:
> 
> https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

Thanks for the link. But I don't see how this makes it easier for me to keep up with new NC versions? This app is pretty basic, but every time I try to release a new version it no longer works...

Right now I'm trying to build a working version for NC24/25, but it doesn't open any of the file formats that should work...I don't know what is going wrong and I can't find anything helpful in the documentation, so currently I'm lost. This means I don't know when there will be a new version compatible with NC24+

**Comment by p-bo** [comment]
> This app is pretty basic, but every time I try to release a new version it no longer works...

Then you are exactly in same position, as [this developer](https://help.nextcloud.com/t/nextcloud-app-development-tutorials-1-step-closer-to-creating-an-app/148288/2), after his this feedback (linked at the beginning of post I linked to) the policy to be more friendly (i.e. document, what changed in "API") was created.

Unfortunately, it is effective since NC 26, but when you manage to port to 25, then from there it should be much easier due this policy.

**Comment by p-bo** [comment]
@v1r0x 
> don't know what is going wrong

So what about to ask on https://help.nextcloud.com/c/dev/11 or devs chat  https://cloud.nextcloud.com/call/xs25tz5y (found on https://nextcloud.com/developer/ ). Or this thread could help eventually:
https://help.nextcloud.com/t/boosting-community-app-development/142442
Last resort would be to look on contacts at people from Engineering team:
https://nextcloud.com/team/
(scroll down)

**Comment by p-bo** [comment]
@v1r0x
And this section in [developer documentation](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/index.html) perhaps?

**Comment by kroko** [comment]
create file `{NCROOT}/config/mimetypemapping.json` and fill with

```json
{
  "dae": ["model/vnd.collada+xml"],
  "glb": ["model/gltf-binary"],
  "gltf": ["model/gltf+json"],
  "obj": ["model/obj-dummy"],
  "fbx": ["model/fbx-dummy"],
  "stl": ["application/sla"],
  "ply": ["model/vnd.ply"],
  "gcode": ["text/x-gcode"]
}
```

fyi, all OOB registred mimetypes reside in `{NCROOT}/resources/config/mimetypemapping.dist.json` [docs](https://docs.nextcloud.com/server/22/admin_manual/configuration_mimetypes/index.html)

**Comment by burner-** [comment]
is there plans to fix this or is this abandonware?

**Comment by v1r0x** [comment]
There are plans to fix this, but I couldn't find a fix yet. I don't know why and how it breaks with every single NC release, so it is hard to find a (long term) solution.

**Comment by kroko** [comment]
> create file `{NCROOT}/config/mimetypemapping.json` and fill with
> 
> ```json
> {
>   "dae": ["model/vnd.collada+xml"],
>   "glb": ["model/gltf-binary"],
>   "gltf": ["model/gltf+json"],
>   "obj": ["model/obj-dummy"],
>   "fbx": ["model/fbx-dummy"],
>   "stl": ["application/sla"],
>   "ply": ["model/vnd.ply"],
>   "gcode": ["text/x-gcode"]
> }
> ```
> 
> fyi, all OOB registred mimetypes reside in `{NCROOT}/resources/config/mimetypemapping.dist.json` [docs](https://docs.nextcloud.com/server/22/admin_manual/configuration_mimetypes/index.html)

@burner- question made me think and well... shameless plug 😄 Spent last few nights on [3D Model Viewer for Nextcloud](https://github.com/WARP-LAB/files_3dmodelviewer) where MIME registering is done on app install listener stage. Built and tested on NC25, but should work on 24, too.

**Comment by v1r0x** [comment]
Yeah if there only would be a way to contribute to existing projects instead of writing shit about it...oh wait there is! It is called _Pull Requests_. Why not use this feature?
Fun fact: Mime type registration is also done in my app. But this seems to be a thing that breaks with every NC release. That's what I said like 5 days ago...right above your comment. So what's your point about "abandoned"? FFS...

Seems like this is no longer needed, so I can close it. "Thanks" to @kroko 🤦‍♂️

**Comment by Simbaclaws** [comment]
I don't think this was abandoned by @v1r0x, It would have been nice to see an update to his plugin. Anyhow for whatever reason @kroko had to rewrite the code, I do appreciate @kroko for rewriting it from scratch. Thank you for your contribution.

I'm sorry I haven't contributed and only complained. I'll try to be more involved next time, I have abandoned my nextcloud install due to other networking issues I couldn't get solved anyways, so I couldn't bother with it at that point.

Thank you both for taking your time to help improve nextcloud, regardless of what others think, my opinion is that you both help the nextcloud community further in a positive way.

**Comment by kroko** [comment]
1) With all due respect at what moment and where did anyone wrote shit about it? IMHO it is great.

2) I needed support for *CADish* files, namely IFC and STEP, and OBJ **with** textures. I was considering PR'in, but looking at it... realistically and provably it would require _rewrite_. Which I did.

3) Finally, your _ad hominish_ and passive aggressive "thanks"? If you're offended, it's your problem. FOSS 🙄

**Comment by v1r0x** [comment]
> I'm sorry I haven't contributed and only complained. I'll try to be more involved next time, I have abandoned my nextcloud install due to other networking issues I couldn't get solved anyways, so I couldn't bother with it at that point.

No problem. I don't mind complaining, testing, brainstorming. Every kind of contribution helps.

> Thank you both for taking your time to help improve nextcloud, regardless of what others think, my opinion is that you both help the nextcloud community further in a positive way.

Thank you! :heart:

**Comment by v1r0x** [comment]
> 1. With all due respect at what moment and where did anyone wrote shit about it? IMHO it is great.

The note in your `README` states that this app is abandoned which is not true. So what's the point of this? If you miss something in this app, it's fine. But making a statement that is not true is not nice. "Writing shit about it" was a harsh phrase...

>     2. I needed support for _CADish_ files, namely IFC and STEP, and OBJ **with** textures. I was considering PR'in, but looking at it... realistically and provably it would require _rewrite_. Which I did.

There is already a draft PR for IFC. Textured OBJ works/worked fine for me. 

>     3. Finally, your _ad hominish_ and passive aggressive "thanks"? If you're offended, it's your problem. FOSS roll_eyes

I'm not offended, but I don't like the way you solved this issue.

**Comment by kroko** [comment]
Stepping forwards -> 
I meant no harm and no diss thus rephrased the reason. I do have used your app historically and thanks again for that. 

Stepping backwards 😄 ->
Could you at least agree, that _abandoned_ is subjective? When I see app that

- does not work on last two NC releases
- the issues pile up
- the features do not grow
- **and** whoever - either the maintainer or issue/feature ticket openers - do not have the initiative to struggle/implement/push forward

for me it seems like beginning of the end, ala _abandoned_. I'm sorry if that touches you personally, which is understandable, given that it is your project, but eventually does not change my evaluation. Or maybe you have idea of revitalising the app (I have such ideas for many projects in the shelf all the time), thus my original phrasing might have been untrue from your perspective.

Forget file types, mimes etc. For example https://github.com/v1r0x/files_3d/issues/63 took me less than hour to implement using localStorage. You could argue, why the OP for that feature request does not implement it. I have two takes on that - the maintainer (yourself) do not use this app on daily basis, thus it does not bother you (and it is _bad_ for the project) and/or the OP does not have that spark, sees no ROI to do it himself (also _bad_ for the project), both lead to abandonment. At the end of the day IMHO we are talking about niche stuff - how many NC users are out there that need such app, really.

I work with 3d models daily, NC is used to share them with clients for evaluation, thus for me there is a reason to keep it up to date, to have persistent GUI, more file types, nice environment lighting, edge drawing etc. I'd like section views, assembly model component toggling and list goes on ad infinitum (albeit features found in Fusion 360 View and Open IFC Viewer would be enough 😆 , unrealistic for no-spare-time effort project of course).

Hope we all are on the same page that everybody is in good will here, mby you understand my position on how I think of _abandonment_, too. Well, at least check out my take on this, comes prebuilt. 😉 Thanks!
