### ISSUE TITLE
Add support for .stl files

### ISSUE THREAD

**Issue by NYH32O99E1Lg** [v1r0x/files_3d#66]
.stl is by far the most common 3d object format. Sites like thingiverse use .stl almost exclusively. 
I use my nextcloud for storing .stl files as i do a lot of 3d printing and modeling
It would be very nice to be able to see them directly in nextcloud without having to convert them to .obj.

I would be very grateful for this

**Comment by v1r0x** [comment]
STL is already supported. Unfortunately, there seems to be a problem with recognizing all formats/formats at all. That's why it doesn't work for some people.
